# Generated by Django 3.1.7 on 2022-07-28 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_auto_20220728_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('first_call', 'Primeiro Atendimento'), ('attendance', 'Atendimento'), ('closure', 'Fechamento'), ('delivery', 'Entrega')], max_length=16, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('concluded', 'Concluído')], default='pending', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='atendida em')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table', verbose_name='Mesa')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Garçom')),
            ],
        ),
    ]
