# Generated by Django 3.1.7 on 2022-07-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('first_call', 'Primeiro Atendimento'), ('attendance', 'Atendimento'), ('closure', 'Fechamento'), ('delivery', 'Entrega')], default='first_call', max_length=16, verbose_name='Tipo'),
        ),
    ]
