# Generated by Django 3.1.7 on 2022-07-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220728_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Item | Cardapio', 'verbose_name_plural': 'Itens | Cardapio'},
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'ordering': ('order_time', 'item'), 'verbose_name': 'Item | Pedido', 'verbose_name_plural': 'Itens | Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesa'},
        ),
        migrations.AlterModelOptions(
            name='waiterorderpad',
            options={'verbose_name': 'Comanda', 'verbose_name_plural': 'Comandas'},
        ),
    ]
